version: '3.8'

services:
  web:
    container_name: django-web
    restart: always
    image: django-web:latest
    build:
      context: ./MyProject/
      dockerfile: Dockerfile.prod
    links:
      - db:db
      - redis:redis
    command: /usr/local/bin/gunicorn MyProject.wsgi:application -w 3 -b :8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./environment/.env.prod
    depends_on:
      - db
  
  db:
    restart: always
    container_name: postgres
    image: postgres:14.3-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./environment/.env.prod.db

  nginx:
    restart: always
    container_name: nginx-proxy
    image: nginx-proxy:latest
    build: 
      context: ./nginx/
      dockerfile: dockerfile
    volumes_from:
      - web
    ports:
      - 80:80
      - 443:443
    links:
      - web:web
    depends_on:
      - web 

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata: