FROM python:3.11-alpine

WORKDIR /src/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /src/
RUN pip install -r requirements.txt

COPY . /src/

EXPOSE 8000

CMD ["gunicorn", "MyProject.wsgi", "--bind", "0.0.0.0:8000"]