FROM nginx:1.23.3-alpine

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/log/nginx/opt
RUN mkdir /etc/nginx/ssl

COPY ./ssl/* /etc/nginx/ssl/

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]