name: Security check - Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} 

    steps:
    - uses: actions/checkout@v3
    - name: Permission 
      run: chmod +x /home/runner/work/Ah-shit-here-we-go-again/Ah-shit-here-we-go-again/MyProject/entrypoint.prod.sh && chmod +x /home/runner/work/Ah-shit-here-we-go-again/Ah-shit-here-we-go-again/MyProject/entrypoint.sh

    - name: Security check - Bandit
      uses: tj-actions/bandit@v5.1
      with:
        python_version: ${{ matrix.python-version }}
        project_path: .
        ignore_failure: true
    
    - name: Check structure
      run: tree .

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Security report
        path: output/security_report.txt
        
